#!/usr/bin/env bash
#Just configure anothernew ubuntu server from scratch as the one done on web-01

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html #new line due to permission denial
sudo chown -R $USER:$USER /var/www/html/index.html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html #sudo added for permission denial error

sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37i\ $redirect" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
err_page="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $err_page" /etc/nginx/sites-available/default
sudo service nginx start
sudo service nginx reload
