#!/usr/bin/env bash
#load-balancing server

# Update system packages
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Set the configuration file with backend servers and load balancing algorithm
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend app-servers

backend app-servers
    balance roundrobin
    server web-01 34.201.161.61:80 check
    server web-02 3.80.18.176:80 check
EOF

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=.*/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo systemctl restart haproxy