#!/usr/bin/env bash
# Check if the password argument is provided

# MySQL dump command
mysqldump -u root -p"$1" --all-databases > backup.sql

# Compress the dump file to tar.gz archive
tar -czf "$(date '+%d-%m-%Y').tar.gz" backup.sql
