#!/usr/bin/env bash
# Check if the password argument is provided

# Get the current date in the required format
date=$(date +%d-%m-%Y)

# MySQL dump command
mysqldump -u root -p"$1" --all-databases > backup.sql

# Compress the dump file to tar.gz archive
tar -czvf "$date.tar.gz" backup.sql
