#!/usr/bin/env bash
#Bad luck and good luckthorugh the if else elif 
COUNTER=1
while [ "$COUNTER" -le 10 ]; do
    if [ $COUNTER -eq 4 ]; then
	echo "bad luck"
    elif [ $COUNTER -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    let COUNTER=COUNTER+1
done
