#!/usr/bin/env bash
# configures nginx so it runs as a user
sudo adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx
sudo sed -i "1i user nginx;" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
