#!/usr/bin/env bash
# a compressed command to configure nginx as user and to listen on port 8080
sed -i 's/listen       80;/listen       8080;/' /etc/nginx/nginx.conf
sed -i 's/^\(user\s*\).*/\1nginx;/' /etc/nginx/nginx.conf
sed -i 's/^\(worker_processes\s*\).*/\12;/' /etc/nginx/nginx.conf
sed -i 's/^\(worker_handle_connections\s*\).*/\1off;/' /etc/nginx/nginx.conf
sed -i 's/^\(keepalive\s*\).*/\15;/' /etc/nginx/nginx.conf
echo -e '\n' >> /etc/nginx/nginx.conf
/usr/sbin/nginx -g 'daemon off;'
